---
title: "south-ridgewood-housing-indicators"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages(tidycensus)
# install.packages(tidyverse)
# install.packages(reshape2)

library(tidyverse)
library(tidycensus)
library(reshape2)
```

## Pulling in ACS indicators for the south ridgewood census block
```{r}
# Connecting to my API
census_api_key("4ce84da33024270337d2c7a57c4b2cbf6bc78f6c")

# Checking out the variable ID's
v9 <- load_variables(2019, "acs5", cache = TRUE)

## loading the 2019-2015 survey
census_19 <- get_acs(
  geography = "tract",
  state = "NY",
  county = (081),
  tract = c(553, 555, 557, 559),
  year = 2019,
  output = "wide",
  survey = "acs5",
  geometry = FALSE,
  variables = c(
    "pop" = "B01003_001",
    "gross_rent_med" = "B25064_001", # median gross rent
    "hh_inc_med" = "B19013_001", # median household income
    "rent_burden_med" = "B25071_001", # median rent burden
    "pov_pct" = "C17002_001", # poverty rate
    "hh_size_avg" = "B25010_001", # average hosehold size
    "occ_units" = "B25003_001", # total occupied units
    "occ_renter_units" = "B25003_003", # renter occupied units
    #"vac_forrent_units" = "B25004_002", # vacant units for rent
    "vac_rented_units" = "B25004_003", # vacant units rented
    "occ_owner"= "B07013_002" # owner occupied
  )
) %>%
  mutate(year = 2019) %>%
  filter(GEOID %in% c(36081055500,
                    36081055300,
                    36081055700,
                    36081055900))

```

```{r}
## loading the 2014-2010 survey ***NOT ALL THE CENSUS TRACTS ARE THERE**
census_14 <- get_acs(
  geography = "tract",
  state = "NY",
  county = (081),
  year = 2014,
  survey = "acs5",
  output = "wide",
  geometry = FALSE,
  variables = c(
    "pop" = "B01003_001",
    "gross_rent_med" = "B25064_001", # median gross rent
    "hh_inc_med" = "B19013_001", # median household income
    "rent_burden_med" = "B25071_001", # median rent burden
    "pov_pct" = "C17002_001", # poverty rate
    "hh_size_avg" = "B25010_001", # average hosehold size
    "occ_units" = "B25003_001", # total occupied units
    "occ_renter_units" = "B25003_003", # renter occupied units
    #"vac_forrent_units" = "B25004_002", # vacant units for rent
    "vac_rented_units" = "B25004_003", # vacant units rented
    "occ_owner"= "B07013_002" # owner occupied
  ))%>% mutate(year = 2014) %>%
  filter(GEOID %in% c(36081055500,
                    36081055300,
                    36081055700,
                    36081055900))
```
```{r}
## loading the 2009-2005 survey ***NOT ALL THE CENSUS TRACTS ARE THERE**
census_09 <- get_acs(
  geography = "tract",
  state = "NY",
  county = (081),
  year = 2009,
  survey = "acs5",
  output = "wide",
  geometry = FALSE,
  variables = c(
    "pop" = "B01003_001",
    "gross_rent_med" = "B25064_001", # median gross rent
    "hh_inc_med" = "B19013_001", # median household income
    "rent_burden_med" = "B25071_001", # median rent burden
    "pov_pct" = "C17002_001", # poverty rate
    "hh_size_avg" = "B25010_001", # average hosehold size
    "occ_units" = "B25003_001", # total occupied units
    "occ_renter_units" = "B25003_003", # renter occupied units
    #"vac_forrent_units" = "B25004_002", # vacant units for rent
    "vac_rented_units" = "B25004_003", # vacant units rented
    "occ_owner"= "B25115_002" # owner occupied
  )) %>%
  mutate(
    year = 2009) %>%
  filter(GEOID %in% c(36081055500,
                    36081055300,
                    36081055700,
                    36081055900))
```
```{r}
# Joining the Two ** CANT USE THIS YET
census_ <-  census_19 %>% 
  bind_rows(census_14, census_09) 

write.csv(census_,"/Users/alanapogostin/Desktop/Urban_Planning_Methods/south_ridgewood_census.csv", row.names = FALSE)
```
# 2015-2019 Data Wrangling
```{r}
rent_burden_indc <- census_ %>%
  select("year","gross_rent_medE", "hh_inc_medE", "rent_burden_medE") %>%
  group_by(year) %>%
  summarise(gross_rent_med_mean = mean(gross_rent_medE),
            hh_inc_med_mean = mean(hh_inc_medE),
            rent_burden_med = mean(rent_burden_medE),
            )
rent_burden_indc <- rent_burden_indc %>%
  mutate(gross_rent_med_mean_change = ((gross_rent_med_mean) - first(gross_rent_med_mean))/ first(gross_rent_med_mean) * 100)

```
# Rent Burden
```{r}
rent_burden_indc <- rent_burden_indc %>%
  mutate(gross_rent_med_mean_change = ((gross_rent_med_mean) - first(gross_rent_med_mean))/ first(gross_rent_med_mean) * 100)

```
# Population Pyramid-----------------------------------------------
#Pulling acs data to make base dataframe for the population pyramid
```{r}
age_by_sex <- get_acs(geography = "tract",
                      state = "NY",
                      county = (081),
                      year = 2019,
                      survey = "acs5",
                      geometry = FALSE,
                      variables = c("m_0_4" = "B01001_003",
                                    "m_5_9"= "B01001_004",
                                    "m_10_14" = "B01001_005",
                                    "m_15_17" = "B01001_006",
                                    "m_18_19" = "B01001_007",
                                    "m_20" = "B01001_008",
                                    "m_21" = "B01001_009",
                                    "m_22_24" = "B01001_010",
                                    "m_25_29" = "B01001_011",
                                    "m_30_34" = "B01001_012",
                                    "m_35_39" = "B01001_013",
                                    "m_40_44" = "B01001_014",
                                    "m_45_49" = "B01001_015",
                                    "m_50_54" = "B01001_016",
                                    "m_55_59" = "B01001_017",
                                    "m_60_61" = "B01001_018",
                                    "m_62_64" = "B01001_019",
                                    "m_65_66" = "B01001_020",
                                    "m_67_69" = "B01001_021",
                                    "m_70_74" = "B01001_022",
                                    "m_75_79" = "B01001_023",
                                    "m_80_84" = "B01001_024",
                                    "m_85p" = "B01001_025",
                                    "f_0_4" = "B01001_027",
                                    "f_5_9" = "B01001_028",
                                    "f_10_14" = "B01001_029",
                                    "f_15_17" = "B01001_030",
                                    "f_18_19" = "B01001_031",
                                    "f_20" = "B01001_032",
                                    "f_21" = "B01001_033",
                                    "f_22_24" = "B01001_034",
                                    "f_25_29" = "B01001_035",
                                    "f_30_34" = "B01001_036",
                                    "f_35_39" = "B01001_037",
                                    "f_40_44" = "B01001_038",
                                    "f_45_49" = "B01001_039",
                                    "f_50_54" = "B01001_040",
                                    "f_55_59" = "B01001_041",
                                    "f_60_61" = "B01001_042",
                                    "f_62_64" = "B01001_043",
                                    "f_65_66" = "B01001_044",
                                    "f_67_69" = "B01001_045",
                                    "f_70_74" = "B01001_046",
                                    "f_75_79" = "B01001_047",
                                    "f_80_84" = "B01001_048",
                                    "f_85p" = "B01001_049")) %>% 
  filter(GEOID %in% c(36081055500,
                    36081055300,
                    36081055700,
                    36081055900)) #narrowing to just the south ridgewood tracts
```

```{r}
# First step of cleaning
age_by_sex_clean  <- age_by_sex %>%
  # select only geoid, variable name and estimate (we don't need MOEs)
  select(GEOID, variable, estimate) %>% 
  # replace any NAs in the data frame for convenience
  mutate(estimate  = if_else(is.na(estimate), 0, estimate)) %>% 
  # spread the data frame with GEOID as column index, and cells filled with estimates (so variable names will be row index)
  spread(GEOID, estimate) %>% 
  # sum up the population in different sex and age group in the selected tracts 
  # *Note: for column names with pure number or with space in the name - add the `` sign to specify it's a column name
  mutate(neighborhood_total = 36081055500 + 36081055300 + 36081055700,36081055900) %>% 
  # keep only the variable name and total population of different sex and age group
  select(variable, neighborhood_total) 


# Calculate the total population in the area for later steps (as the denominator for calculating the proportions)
population_total <- sum(age_by_sex_clean$neighborhood_total, na.rm = TRUE)

# Further cleaning
age_by_sex_clean_new <- age_by_sex_clean  %>%
  # extract gender information from the first letter of the varialbe name and save as a column
  mutate(gender = if_else(str_sub(variable, 1, 1) == "m", "male", "female")) %>%
  # extract age group information from the rest of the varialbe name and save as a column
  mutate(age_group = str_sub(variable,3,-1)) %>%
  # drop variable name column
  select(-variable) %>%
  # spread the data frame with age_group as column index, and cells filled with neighborhood_total (so gender will be row index)
  spread(age_group, neighborhood_total) %>%
  # aggregate some of the age groups since ACS have breakdowns in some of them
  mutate(`15_19` = `15_17` + `18_19`,
         `20_24`  = `20` + `21` + `22_24`,
         `60_64`  = `60_61` + `62_64`,
         `65_69` = `65_66` + `67_69`) %>%
  # drop the original breakdown columns
  select(-`15_17`,- `18_19`, -`20`, -`21`, -`22_24`, -`60_61`, -`62_64`, -`65_66`, -`67_69`) %>%
  # restructure the dataframe
  melt(id.vars = "gender") %>%
  # break the spread table into single records, and rename the columns
  select(gender, age_group = variable, count = value) %>%
  # spread the table with gender as column index, and data cell with population counts (so age_group becomes the row index)
  spread(gender, count)

age_by_sex_dataframe <- age_by_sex_clean_new %>%
  # set the male proportion stats to the negative values so that the bars will go to the opposite direction
  mutate(male = -male) %>%
  # keep only age_group, male (negative value) and female in the data frame
  select(age_group, male, female) %>%
  # calculate the proportion of each group, using total population as the denominator
  mutate(male_pct = male/population_total,
         female_pct = female/population_total )

age_by_sex_dataframe <- age_by_sex_dataframe %>%
  # keep only the age_group, proportion columns of male and female
  select(age_group, male_pct, female_pct)%>%
  # restructure the dataframe
  melt(id.vars = "age_group") %>%
  # add the full gender information column for later coloring the bars in the graphs
  mutate(Gender = if_else(str_sub(variable, 1, 1) == "m", "Male", "Female")) %>%
  # drop the variable column since we turned it into the Gender column
  select(-variable) %>%
  # modify the age_group text, replace "_" with " to " to make it user-friendly
  mutate(age_group = str_replace(age_group, "[_]", " to ")) %>%
  # 85p is the only one without "_", we need to specify the change in this case
  mutate(age_group = if_else(age_group == "85p", "85 and over", age_group)) %>%
  # add the level to different age groups so that it will come out with proper order
  mutate(age_group = fct_relevel(age_group, age_level))

#Summary stats
total_gender <- age_by_sex_dataframe %>%
  select("Gender", "value") %>%
  group_by(Gender)%>%
  summarize(total = sum(value))


# set up the plot, the dataset name, x axis will be age group, and y axis will be percentage 
# we also fill the bars with colors based on gender information
pop_pyramid <- ggplot(age_by_sex_dataframe, aes(x = age_group, y = value, fill = Gender)) + 
  # plot the age by sex data frame with bar graphs
  geom_bar(stat = "identity") +
  scale_y_continuous(limits = c(-0.1,0.1), breaks = seq(-0.1, 0.1, 0.02), labels = scales::percent)+
    coord_flip()
  labs(x = "Age Group",
       y = "Percentage",
       title = ("Population Pyramid - South Ridgewood, ACS 2015-2019")
       ) 

# show the plot
pop_pyramid
```
# Population Pyramid
# Pop Change graph and data wrangle
```{r}
pop_change <- census_ %>%
  select("year","popE") %>%
  group_by(year) %>%
  summarise(pop = sum(popE))

gg_pop_change <- ggplot(pop_change, aes(x = as.numeric(year), y = pop)) +
  geom_bar(stat="identity") +
  scale_y_continuous(n.breaks = 10) +
  scale_x_continuous(label = c(0, 2009, 2014, 2019))+
  #scale_x_continuous(labels = "year")+
  geom_text(aes(label=pop), vjust=-0.3, size=3.5)+
  labs(title = "Population of Southern Ridgewood",
       x = "Year",
       y = "Number of Residents") +
  theme_bw()

gg_pop_change
```

# Poverty
```{r}
poverty <- census_ %>%
  group_by(year) %>%
  summarise(pov = sum(pov_pctE),
            pop = sum(popE),
            pov_pct =(pov/pop)
            )
  geom_bar(stat="identity") +
  scale_y_continuous(labels = scales::percent,
                     n.breaks = 10) +
  scale_x_continuous(label = c(0, 2009, 2014, 2019))+
  labs(title = "Poverty Rate in Southern Ridgewood",
       x = "Year",
       y = "Poverty Rate (%)") +
  theme_bw()
gg_poverty
```

# Ownership-----------------------------------
```{r}
owner_occ <- census_ %>%
  select("year","occ_unitsE", "occ_ownerE") %>%
  mutate(pct_owner_occ = (occ_ownerE/occ_unitsE)) %>%
  group_by(year) %>%
  summarize(pct_owner_occ_mean = mean(pct_owner_occ),
            occ_units_mean = mean(occ_unitsE),
            occ_ownerE = mean(occ_ownerE))

gg_owner_occ <- ggplot(owner_occ, aes(x = year, y = pct_owner_occ_mean)) +
  geom_bar(stat="identity") +
  scale_y_continuous(labels = scales::percent) +
    scale_x_continuous(label = c(0, 2009, 2014, 2019))+
   #geom_text(aes(label=pct_owner_occ_mean), vjust=-0.3, size=3.5)+
  labs(title = "Percent of total Occupied Units that are Owner Occupied",
       x = "Year",
       y = "Percent Owner Occupied") +
  theme_bw()
gg_owner_occ
```




